name: Unit Tests
on: [push, pull_request]
jobs:
  go_tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./...
        env:
          CHROMEDP_CHROME_PATH: google-chrome-stable
