name: Unit Tests
on: [push, pull_request]
jobs:
  go_tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            gofmt -d .
            exit 1
          fi
      - run: go vet ./...
      - run: go build ./...
      - run: go test ./...
        env:
          CHROMEDP_CHROME_PATH: google-chrome-stable
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
        with:
          go-version-file: go.mod
